export const projectsArr = [
  {
    id: 1,
    title: "Holidaze",
    description: "Booking website for hotels. Built with React, TypeScript, Tailwind CSS, Vite and Noroff API. Deployed with Netlify.",
    image: "/src/assets/images/application-screenshot-holidaze.png",
    url: "https://holidaze-thea-final-exam.netlify.app/",
    logo: "/src/assets/images/holidaze-logo.svg",
    bg: "holidaze",
    tailwind: true,
    react: true,
    js: false,
    typescript: true,
    bootstrap: false,
    sass: false,
    cssModules: false,
  },
  {
    id: 2,
    title: "Bazaar",
    description: "Live auction website. Built with Vanilla JS, SCSS, Bootstrap and Noroff API. Deployed with GitHub Pages. Including unit-tests with Jest and e2e-tests with Cypress running on workflows.",
    image: "/src/assets/images/application-screenshot-bazaar.png",
    url: "https://dwnwnd.github.io/SemesterProject2_TheaOland/",
    logo: "/src/assets/images/bazaar-logo.svg",
    bg: "bazaar",
    tailwind: false,
    react: false,
    js: true,
    typescript: false,
    bootstrap: true,
    sass: true,
    cssModules: false,
  },
  {
    id: 3,
    title: "Lazz",
    description: "E-commerce website. Built with React, CSS modules, Vite and Noroff API. Deployed with Netlify.",
    image: "/src/assets/images/application-screenshot-lazz.png",
    url: "https://lazz.netlify.app/",
    logo: "/src/assets/images/lazz-logo.svg",
    bg: "lazz",
    tailwind: false,
    react: true,
    js: false,
    typescript: false,
    bootstrap: false,
    sass: false,
    cssModules: true,
  },
];
