import holidazeScreenshot from "../screenshots/application-screenshot-holidaze.png";
import holidazeLogo from "../logos/holidaze-logo.svg";

import bazaarScreenshot from "../screenshots/application-screenshot-bazaar.png";
import bazaarLogo from "../logos/bazaar-logo.svg";

import lazzScreenshot from "../screenshots/application-screenshot-lazz.png";
import lazzLogo from "../logos/lazz-logo.svg";

import thecheckinScreenshot from "../screenshots/application-screenshot-thecheckin.png";
import thecheckinLogo from "../logos/thecheckin-logo.svg";

import dwnwndScreenshot from "../screenshots/application-screenshot-dwnwnd.png";
import dwnwndLogo from "../logos/dwnwnd-logo.svg";

import letsmovetothailandScreenshot from "../screenshots/application-screenshot-letsmovetothailand.png";
import letsmovetothailandLogo from "../logos/letsmovetothailand-logo.svg";

import levitalScreenshot from "../screenshots/application-screenshot-levital.png";
import levitalLogo from "../logos/levital-logo.svg";

import atScreenshot from "../screenshots/application-screenshot-at.png";
import atLogo from "../logos/at-logo.svg";

// import rainydaysScreenshot from "../screenshots/application-screenshot-rainydays.png";
// import rainydaysLogo from "../logos/rainydays-logo.svg";

import csmScreenshot from "../screenshots/application-screenshot-csm.png";
import csmLogo from "../logos/csm-logo.svg";

import microticScreenshot from "../screenshots/application-screenshot-microtic.png";
import microticLogo from "../logos/microtic-logo.svg";

export const projectsArr = [
  {
    id: 1,
    title: "Holidaze",
    description: "Booking website for hotels. Built with React, TypeScript, Tailwind CSS, Vite and Noroff API. Deployed with Netlify.",
    image: holidazeScreenshot,
    url: "https://holidaze-thea-final-exam.netlify.app/",
    repo: "https://github.com/DWNWND/Final-Exam-Thea",
    logo: holidazeLogo,
    association: "academic",
    finished: true,
    grading: 10,
    tailwind: true,
    react: true,
    js: false,
    typescript: true,
    bootstrap: false,
    sass: false,
    cssModules: false,
    css: false,
    html: false,
  },
  {
    id: 2,
    title: "Bazaar",
    description: "Live auction website. Built with Vanilla JS, SCSS, Bootstrap and Noroff API. Deployed with GitHub Pages. Including unit-tests with Jest and e2e-tests with Cypress running on workflows.",
    image: bazaarScreenshot,
    url: "https://dwnwnd.github.io/SemesterProject2_TheaOland/",
    repo: "https://github.com/DWNWND/SemesterProject2_TheaOland",
    logo: bazaarLogo,
    association: "academic",
    finished: true,
    grading: 5,
    tailwind: false,
    react: false,
    js: true,
    typescript: false,
    bootstrap: true,
    sass: true,
    cssModules: false,
    css: false,
    html: false,
  },
  {
    id: 3,
    title: "Lazz",
    description: "E-commerce website. Built with React, CSS modules, Vite and Noroff API. Deployed with Netlify.",
    image: lazzScreenshot,
    url: "https://lazz.netlify.app/",
    repo: "https://github.com/DWNWND/Frontend-Frameworks-CA-Thea",
    logo: lazzLogo,
    association: "academic",
    finished: true,
    grading: 6,
    tailwind: false,
    react: true,
    js: false,
    typescript: false,
    bootstrap: false,
    sass: false,
    cssModules: true,
    css: false,
    html: false,
  },
  {
    id: 4,
    title: "The Checkin",
    description: "Social media website. Built with Vanilla JS, HTML, Bootstrap and Noroff API. Deployed with Netlify.",
    image: thecheckinScreenshot,
    url: "https://poetic-syrniki-8982a1.netlify.app/",
    repo: "https://github.com/DWNWND/css-frameworks-ca-thea",
    logo: thecheckinLogo,
    association: "academic",
    finished: true,
    grading: 6,
    tailwind: false,
    react: false,
    js: true,
    typescript: false,
    bootstrap: true,
    sass: false,
    cssModules: false,
    css: false,
    html: true,
  },
  {
    id: 5,
    title: "dwnwnd",
    description: "Personal business website. Built with Vanilla JS, HTML and CSS, using a personal CMS. Deployed on Netlify. This website is still in development.",
    image: dwnwndScreenshot,
    url: "https://calm-lollipop-e6119a.netlify.app/",
    logo: dwnwndLogo,
    association: "personal",
    finished: false,
    tailwind: false,
    react: false,
    js: true,
    typescript: false,
    bootstrap: false,
    sass: false,
    cssModules: false,
    css: true,
    html: true,
  },
  {
    id: 6,
    title: "Lets Move To Thailand",
    description: "Checklist website. Built with Vanilla JS, HTML, CSS and Bootstrap. Deployed with Netlify.",
    image: letsmovetothailandScreenshot,
    url: "https://letsmovetothailand.netlify.app/",
    logo: letsmovetothailandLogo,
    association: "personal",
    finished: true,
    tailwind: false,
    react: false,
    js: true,
    typescript: false,
    bootstrap: false,
    sass: false,
    cssModules: false,
    css: true,
    html: true,
  },
  {
    id: 7,
    title: "Levital",
    description: "Business landing page. Built with Vanilla JS, HTML and CSS. Deployed with Netlify.",
    image: levitalScreenshot,
    url: "https://legendary-froyo-8b8366.netlify.app/",
    logo: levitalLogo,
    association: "professional",
    finished: false,
    tailwind: false,
    react: false,
    js: true,
    typescript: false,
    bootstrap: false,
    sass: false,
    cssModules: false,
    css: true,
    html: true,
  },
  {
    id: 8,
    title: "Andrea & Torjus",
    description: "Wedding invitation. Built with Vanilla JS, HTML and CSS. Deployed with Netlify.",
    image: atScreenshot,
    url: "https://dancing-hamster-e6e01c.netlify.app/",
    logo: atLogo,
    association: "professional",
    finished: true,
    tailwind: false,
    react: false,
    js: true,
    typescript: false,
    bootstrap: false,
    sass: false,
    cssModules: false,
    css: true,
    html: true,
  },
  {
    id: 9,
    title: "Community Science Museum",
    description: "Business landing page. Built with HTML and CSS. Deployed with Netlify.",
    image: csmScreenshot,
    url: "https://dainty-pony-7fe7b6.netlify.app/",
    repo: "https://github.com/DWNWND/SemesterProject1_Thea-Oland",
    logo: csmLogo,
    association: "academic",
    finished: true,
    grading: 5,
    tailwind: false,
    react: false,
    js: false,
    typescript: false,
    bootstrap: false,
    sass: false,
    cssModules: false,
    css: true,
    html: true,
  },
  // {
  //   id: 10,
  //   title: "Rainy Days",
  //   description: "E-commerce. Built with HTML and CSS. Deployed with Netlify.",
  //   image: rainydaysScreenshot,
  //   url: "https://cosmic-chebakia-e790e2.netlify.app/",
  //   logo: rainydaysLogo,
  //   association: "academic",
  //   finished: true,
  //   grading: 6,
  //   tailwind: false,
  //   react: false,
  //   js: false,
  //   typescript: false,
  //   bootstrap: false,
  //   sass: false,
  //   cssModules: false,
  //   css: true,
  //   html: true,
  // },
  {
    id: 11,
    title: "Microtic",
    description: "Blog. Built with HTML, CSS and personal CMS. Deployed with Netlify.",
    image: microticScreenshot,
    url: "https://spiffy-halva-4ffb7c.netlify.app/",
    repo: "https://github.com/DWNWND/project-exam-1-DWNWND",
    logo: microticLogo,
    association: "academic",
    finished: true,
    grading: 5,
    tailwind: false,
    react: false,
    js: false,
    typescript: false,
    bootstrap: false,
    sass: false,
    cssModules: false,
    css: true,
    html: true,
  },
];
